name: Inasx
description: "EnX OS - Mine Inasx"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Essencial para o som de boot da Splash e os bipes de ativação
  audioplayers: ^5.2.1
  http: ^1.2.1
  intl: ^0.19.0
  system_info2: ^4.1.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  battery_plus: ^6.1.0
  
  # NOVOS: Essenciais para o Worker rodar em Background e enviar notificações
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Gerador de ícones para o APK não ficar com o logo do Flutter
  flutter_launcher_icons: ^0.13.1

# Configuração do Ícone do App
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/miner.png"
  adaptive_icon_background: "#020817"
  adaptive_icon_foreground: "assets/images/miner.png"

flutter:
  uses-material-design: true

  # DECLARAÇÃO DE ASSETS
  assets:
    - assets/images/logo.png
    - assets/images/miner.png
    - assets/sounds/into.mp3
    - assets/sounds/coin.mp3
    - assets/images/enx.png
    - assets/images/dwellers.png
    - assets/images/inasx.png
    - assets/images/pigeon.png
    - assets/images/fmarket.png